CREATE TABLE [dbo].[Games](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[GameId] [nvarchar](128) NULL,
	[Date] [datetimeoffset](7) NOT NULL,
    [TimeOfDay] [nvarchar](10) NOT NULL,
	[GameType] [int] NOT NULL,
	[Innings] [int] NOT NULL,
	[HomeScore_Runs] [int] NOT NULL,
	[HomeScore_Hits] [int] NOT NULL,
	[HomeScore_Errors] [int] NOT NULL,
	[HomeScore_StrikeOuts] [int] NOT NULL,
	[HomeScore_StolenBases] [int] NOT NULL,
	[HomeScore_HomeRuns] [int] NOT NULL,
	[AwayScore_Runs] [int] NOT NULL,
	[AwayScore_Hits] [int] NOT NULL,
	[AwayScore_Errors] [int] NOT NULL,
	[AwayScore_StrikeOuts] [int] NOT NULL,
	[AwayScore_StolenBases] [int] NOT NULL,
	[AwayScore_HomeRuns] [int] NOT NULL,
	[HomeTeamId] [int] NOT NULL,
	[HomeRecord_Wins] [int] NULL,
	[HomeRecord_Losses] [int] NULL,
	[HomeRecord_Era] [decimal](19, 9) NULL,
	[HomeRecord_Saves] [int] NULL,
	[HomeRecord_Opportunities] [int] NULL,
	[AwayTeamId] [int] NOT NULL,
	[AwayRecord_Wins] [int] NULL,
	[AwayRecord_Losses] [int] NULL,
	[AwayRecord_Era] [decimal](19, 9) NULL,
	[AwayRecord_Saves] [int] NULL,
	[AwayRecord_Opportunities] [int] NULL,
	[WinningPitcherId] [int] NOT NULL,
	[WinningPitcherRecord_Wins] [int] NULL,
	[WinningPitcherRecord_Losses] [int] NULL,
	[WinningPitcherRecord_Era] [decimal](19, 9) NULL,
	[WinningPitcherRecord_Saves] [int] NULL,
	[WinningPitcherRecord_Opportunities] [int] NULL,
	[LosingPitcherId] [int] NOT NULL,
	[LosingPitcherRecord_Wins] [int] NULL,
	[LosingPitcherRecord_Losses] [int] NULL,
	[LosingPitcherRecord_Era] [decimal](19, 9) NULL,
	[LosingPitcherRecord_Saves] [int] NULL,
	[LosingPitcherRecord_Opportunities] [int] NULL,
	[SavingPitcherId] [int] NULL,
	[SavingPitcherRecord_Wins] [int] NULL,
	[SavingPitcherRecord_Losses] [int] NULL,
	[SavingPitcherRecord_Era] [decimal](19, 9) NULL,
	[SavingPitcherRecord_Saves] [int] NULL,
	[SavingPitcherRecord_Opportunities] [int] NULL,
    CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [UQ_Games_GameId] UNIQUE ([GameId])
)
