
using System;
using Infrastructure.DataAccess;
using Microsoft.OData.Edm;

namespace MlbDataPump
{
    public sealed class MlbModel : AutoGeneratedProxy
    {
        public MlbModel(Uri url) : base(url)
        {
        }

        public override IEdmModel GetModel()
        {
            throw new NotImplementedException();
        }
    }
}
